/**
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.umlTextual.impl;

import br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage;
import br.ufes.mdd.umltextual.umlTextual.UseCase;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Use Case</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseImpl#getIncludedUseCase <em>Included Use Case</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseImpl#getExtendedUseCase <em>Extended Use Case</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseImpl#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UseCaseImpl extends UseCaseElementImpl implements UseCase
{
  /**
   * The cached value of the '{@link #getIncludedUseCase() <em>Included Use Case</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncludedUseCase()
   * @generated
   * @ordered
   */
  protected EList<UseCase> includedUseCase;

  /**
   * The cached value of the '{@link #getExtendedUseCase() <em>Extended Use Case</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtendedUseCase()
   * @generated
   * @ordered
   */
  protected EList<UseCase> extendedUseCase;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UseCaseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UmlTextualPackage.Literals.USE_CASE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<UseCase> getIncludedUseCase()
  {
    if (includedUseCase == null)
    {
      includedUseCase = new EObjectResolvingEList<UseCase>(UseCase.class, this, UmlTextualPackage.USE_CASE__INCLUDED_USE_CASE);
    }
    return includedUseCase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<UseCase> getExtendedUseCase()
  {
    if (extendedUseCase == null)
    {
      extendedUseCase = new EObjectResolvingEList<UseCase>(UseCase.class, this, UmlTextualPackage.USE_CASE__EXTENDED_USE_CASE);
    }
    return extendedUseCase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UmlTextualPackage.USE_CASE__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UmlTextualPackage.USE_CASE__INCLUDED_USE_CASE:
        return getIncludedUseCase();
      case UmlTextualPackage.USE_CASE__EXTENDED_USE_CASE:
        return getExtendedUseCase();
      case UmlTextualPackage.USE_CASE__DESCRIPTION:
        return getDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UmlTextualPackage.USE_CASE__INCLUDED_USE_CASE:
        getIncludedUseCase().clear();
        getIncludedUseCase().addAll((Collection<? extends UseCase>)newValue);
        return;
      case UmlTextualPackage.USE_CASE__EXTENDED_USE_CASE:
        getExtendedUseCase().clear();
        getExtendedUseCase().addAll((Collection<? extends UseCase>)newValue);
        return;
      case UmlTextualPackage.USE_CASE__DESCRIPTION:
        setDescription((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UmlTextualPackage.USE_CASE__INCLUDED_USE_CASE:
        getIncludedUseCase().clear();
        return;
      case UmlTextualPackage.USE_CASE__EXTENDED_USE_CASE:
        getExtendedUseCase().clear();
        return;
      case UmlTextualPackage.USE_CASE__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UmlTextualPackage.USE_CASE__INCLUDED_USE_CASE:
        return includedUseCase != null && !includedUseCase.isEmpty();
      case UmlTextualPackage.USE_CASE__EXTENDED_USE_CASE:
        return extendedUseCase != null && !extendedUseCase.isEmpty();
      case UmlTextualPackage.USE_CASE__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (description: ");
    result.append(description);
    result.append(')');
    return result.toString();
  }

} //UseCaseImpl
