/**
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.umlTextual;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor Use Case Association</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.ActorUseCaseAssociation#getUseCase <em>Use Case</em>}</li>
 * </ul>
 *
 * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getActorUseCaseAssociation()
 * @model
 * @generated
 */
public interface ActorUseCaseAssociation extends EObject
{
  /**
   * Returns the value of the '<em><b>Use Case</b></em>' reference list.
   * The list contents are of type {@link br.ufes.mdd.umltextual.umlTextual.UseCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Case</em>' reference list.
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getActorUseCaseAssociation_UseCase()
   * @model
   * @generated
   */
  EList<UseCase> getUseCase();

} // ActorUseCaseAssociation
