/**
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.umlTextual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aggregation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Aggregation#getNavigation <em>Navigation</em>}</li>
 * </ul>
 *
 * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getAggregation()
 * @model
 * @generated
 */
public interface Aggregation extends AssociationConnector
{
  /**
   * Returns the value of the '<em><b>Navigation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Navigation</em>' attribute.
   * @see #setNavigation(String)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getAggregation_Navigation()
   * @model
   * @generated
   */
  String getNavigation();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.Aggregation#getNavigation <em>Navigation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Navigation</em>' attribute.
   * @see #getNavigation()
   * @generated
   */
  void setNavigation(String value);

} // Aggregation
