/**
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.umlTextual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Association Connector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getClass1 <em>Class1</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getMultiplicity1 <em>Multiplicity1</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getClass2 <em>Class2</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getMultiplicity2 <em>Multiplicity2</em>}</li>
 * </ul>
 *
 * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getAssociationConnector()
 * @model
 * @generated
 */
public interface AssociationConnector extends Element
{
  /**
   * Returns the value of the '<em><b>Class1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class1</em>' reference.
   * @see #setClass1(br.ufes.mdd.umltextual.umlTextual.Class)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getAssociationConnector_Class1()
   * @model
   * @generated
   */
  br.ufes.mdd.umltextual.umlTextual.Class getClass1();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getClass1 <em>Class1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class1</em>' reference.
   * @see #getClass1()
   * @generated
   */
  void setClass1(br.ufes.mdd.umltextual.umlTextual.Class value);

  /**
   * Returns the value of the '<em><b>Multiplicity1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicity1</em>' attribute.
   * @see #setMultiplicity1(String)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getAssociationConnector_Multiplicity1()
   * @model
   * @generated
   */
  String getMultiplicity1();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getMultiplicity1 <em>Multiplicity1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicity1</em>' attribute.
   * @see #getMultiplicity1()
   * @generated
   */
  void setMultiplicity1(String value);

  /**
   * Returns the value of the '<em><b>Class2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class2</em>' reference.
   * @see #setClass2(br.ufes.mdd.umltextual.umlTextual.Class)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getAssociationConnector_Class2()
   * @model
   * @generated
   */
  br.ufes.mdd.umltextual.umlTextual.Class getClass2();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getClass2 <em>Class2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class2</em>' reference.
   * @see #getClass2()
   * @generated
   */
  void setClass2(br.ufes.mdd.umltextual.umlTextual.Class value);

  /**
   * Returns the value of the '<em><b>Multiplicity2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicity2</em>' attribute.
   * @see #setMultiplicity2(String)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getAssociationConnector_Multiplicity2()
   * @model
   * @generated
   */
  String getMultiplicity2();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getMultiplicity2 <em>Multiplicity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicity2</em>' attribute.
   * @see #getMultiplicity2()
   * @generated
   */
  void setMultiplicity2(String value);

} // AssociationConnector
