/**
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.umlTextual;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Class#getStereotype <em>Stereotype</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Class#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Class#getParentClass <em>Parent Class</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Class#getInterface <em>Interface</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Class#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Class#getMethods <em>Methods</em>}</li>
 * </ul>
 *
 * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getClass_()
 * @model
 * @generated
 */
public interface Class extends Element
{
  /**
   * Returns the value of the '<em><b>Stereotype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stereotype</em>' attribute.
   * @see #setStereotype(String)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getClass_Stereotype()
   * @model
   * @generated
   */
  String getStereotype();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.Class#getStereotype <em>Stereotype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stereotype</em>' attribute.
   * @see #getStereotype()
   * @generated
   */
  void setStereotype(String value);

  /**
   * Returns the value of the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibility</em>' attribute.
   * @see #setVisibility(String)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getClass_Visibility()
   * @model
   * @generated
   */
  String getVisibility();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.Class#getVisibility <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibility</em>' attribute.
   * @see #getVisibility()
   * @generated
   */
  void setVisibility(String value);

  /**
   * Returns the value of the '<em><b>Parent Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent Class</em>' reference.
   * @see #setParentClass(Class)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getClass_ParentClass()
   * @model
   * @generated
   */
  Class getParentClass();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.Class#getParentClass <em>Parent Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent Class</em>' reference.
   * @see #getParentClass()
   * @generated
   */
  void setParentClass(Class value);

  /**
   * Returns the value of the '<em><b>Interface</b></em>' reference list.
   * The list contents are of type {@link br.ufes.mdd.umltextual.umlTextual.Interface}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface</em>' reference list.
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getClass_Interface()
   * @model
   * @generated
   */
  EList<Interface> getInterface();

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.mdd.umltextual.umlTextual.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getClass_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Methods</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.mdd.umltextual.umlTextual.Method}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methods</em>' containment reference list.
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getClass_Methods()
   * @model containment="true"
   * @generated
   */
  EList<Method> getMethods();

} // Class
