/**
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.umlTextual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Specific Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getDomainSpecificType()
 * @model
 * @generated
 */
public interface DomainSpecificType extends AttributeType
{
} // DomainSpecificType
