/**
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.umlTextual;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Package#getType <em>Type</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Package#getName <em>Name</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Package#getClasses <em>Classes</em>}</li>
 *   <li>{@link br.ufes.mdd.umltextual.umlTextual.Package#getAssociations <em>Associations</em>}</li>
 * </ul>
 *
 * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getPackage()
 * @model
 * @generated
 */
public interface Package extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getPackage_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.Package#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getPackage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.ufes.mdd.umltextual.umlTextual.Package#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.mdd.umltextual.umlTextual.Class}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getPackage_Classes()
   * @model containment="true"
   * @generated
   */
  EList<br.ufes.mdd.umltextual.umlTextual.Class> getClasses();

  /**
   * Returns the value of the '<em><b>Associations</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Associations</em>' containment reference list.
   * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage#getPackage_Associations()
   * @model containment="true"
   * @generated
   */
  EList<AssociationConnector> getAssociations();

} // Package
