/**
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.umlTextual;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.ufes.mdd.umltextual.umlTextual.UmlTextualFactory
 * @model kind="package"
 * @generated
 */
public interface UmlTextualPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "umlTextual";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ufes.br/mdd/umltextual/UmlTextual";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "umlTextual";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UmlTextualPackage eINSTANCE = br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl.init();

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.ModelImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ModelElementImpl <em>Model Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.ModelElementImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getModelElement()
   * @generated
   */
  int MODEL_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Model Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.PackageImpl <em>Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.PackageImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getPackage()
   * @generated
   */
  int PACKAGE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__NAME = MODEL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Instantiable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__INSTANTIABLE = MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__TYPE = MODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Parent Package</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__PARENT_PACKAGE = MODEL_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Domain Specific Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__DOMAIN_SPECIFIC_TYPES = MODEL_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__ELEMENTS = MODEL_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_FEATURE_COUNT = MODEL_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.ElementImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.ClassImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getClass_()
   * @generated
   */
  int CLASS = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Stereotype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__STEREOTYPE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__VISIBILITY = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Parent Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__PARENT_CLASS = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Interface</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__INTERFACE = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__ATTRIBUTES = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Methods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__METHODS = ELEMENT_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.InterfaceImpl <em>Interface</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.InterfaceImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getInterface()
   * @generated
   */
  int INTERFACE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Stereotype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__STEREOTYPE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__VISIBILITY = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Parent Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__PARENT_CLASS = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__ATTRIBUTES = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Interface</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.AttributeTypeImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAttributeType()
   * @generated
   */
  int ATTRIBUTE_TYPE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Domain Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE__DOMAIN_TYPE = 1;

  /**
   * The number of structural features of the '<em>Attribute Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.DomainSpecificTypeImpl <em>Domain Specific Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.DomainSpecificTypeImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getDomainSpecificType()
   * @generated
   */
  int DOMAIN_SPECIFIC_TYPE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_SPECIFIC_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_SPECIFIC_TYPE__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Domain Specific Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_SPECIFIC_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.AttributeImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 8;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__VISIBILITY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 2;

  /**
   * The feature id for the '<em><b>Multiplicity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__MULTIPLICITY = 3;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.MethodImpl <em>Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.MethodImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getMethod()
   * @generated
   */
  int METHOD = 9;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__VISIBILITY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__NAME = 1;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__PARAMETERS = 2;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__RETURN_TYPE = 3;

  /**
   * The number of structural features of the '<em>Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.ParameterImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameter Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__PARAMETER_TYPE = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AssociationConnectorImpl <em>Association Connector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.AssociationConnectorImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAssociationConnector()
   * @generated
   */
  int ASSOCIATION_CONNECTOR = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_CONNECTOR__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Class1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_CONNECTOR__CLASS1 = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Multiplicity1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_CONNECTOR__MULTIPLICITY1 = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Class2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_CONNECTOR__CLASS2 = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Multiplicity2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_CONNECTOR__MULTIPLICITY2 = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Association Connector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_CONNECTOR_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AssociationImpl <em>Association</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.AssociationImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAssociation()
   * @generated
   */
  int ASSOCIATION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__NAME = ASSOCIATION_CONNECTOR__NAME;

  /**
   * The feature id for the '<em><b>Class1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__CLASS1 = ASSOCIATION_CONNECTOR__CLASS1;

  /**
   * The feature id for the '<em><b>Multiplicity1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__MULTIPLICITY1 = ASSOCIATION_CONNECTOR__MULTIPLICITY1;

  /**
   * The feature id for the '<em><b>Class2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__CLASS2 = ASSOCIATION_CONNECTOR__CLASS2;

  /**
   * The feature id for the '<em><b>Multiplicity2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__MULTIPLICITY2 = ASSOCIATION_CONNECTOR__MULTIPLICITY2;

  /**
   * The feature id for the '<em><b>Navigation1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__NAVIGATION1 = ASSOCIATION_CONNECTOR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Navigation2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__NAVIGATION2 = ASSOCIATION_CONNECTOR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__CLASS = ASSOCIATION_CONNECTOR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Association</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FEATURE_COUNT = ASSOCIATION_CONNECTOR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AggregationImpl <em>Aggregation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.AggregationImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAggregation()
   * @generated
   */
  int AGGREGATION = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION__NAME = ASSOCIATION_CONNECTOR__NAME;

  /**
   * The feature id for the '<em><b>Class1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION__CLASS1 = ASSOCIATION_CONNECTOR__CLASS1;

  /**
   * The feature id for the '<em><b>Multiplicity1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION__MULTIPLICITY1 = ASSOCIATION_CONNECTOR__MULTIPLICITY1;

  /**
   * The feature id for the '<em><b>Class2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION__CLASS2 = ASSOCIATION_CONNECTOR__CLASS2;

  /**
   * The feature id for the '<em><b>Multiplicity2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION__MULTIPLICITY2 = ASSOCIATION_CONNECTOR__MULTIPLICITY2;

  /**
   * The feature id for the '<em><b>Navigation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION__NAVIGATION = ASSOCIATION_CONNECTOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Aggregation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION_FEATURE_COUNT = ASSOCIATION_CONNECTOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.CompositionImpl <em>Composition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.CompositionImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getComposition()
   * @generated
   */
  int COMPOSITION = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__NAME = ASSOCIATION_CONNECTOR__NAME;

  /**
   * The feature id for the '<em><b>Class1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__CLASS1 = ASSOCIATION_CONNECTOR__CLASS1;

  /**
   * The feature id for the '<em><b>Multiplicity1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__MULTIPLICITY1 = ASSOCIATION_CONNECTOR__MULTIPLICITY1;

  /**
   * The feature id for the '<em><b>Class2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__CLASS2 = ASSOCIATION_CONNECTOR__CLASS2;

  /**
   * The feature id for the '<em><b>Multiplicity2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__MULTIPLICITY2 = ASSOCIATION_CONNECTOR__MULTIPLICITY2;

  /**
   * The feature id for the '<em><b>Navigation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__NAVIGATION = ASSOCIATION_CONNECTOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Composition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_FEATURE_COUNT = ASSOCIATION_CONNECTOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseDiagramImpl <em>Use Case Diagram</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UseCaseDiagramImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getUseCaseDiagram()
   * @generated
   */
  int USE_CASE_DIAGRAM = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DIAGRAM__NAME = MODEL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DIAGRAM__ELEMENTS = MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Use Case Diagram</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_DIAGRAM_FEATURE_COUNT = MODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseElementImpl <em>Use Case Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UseCaseElementImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getUseCaseElement()
   * @generated
   */
  int USE_CASE_ELEMENT = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Use Case Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ActorImpl <em>Actor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.ActorImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getActor()
   * @generated
   */
  int ACTOR = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__NAME = USE_CASE_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__VISIBILITY = USE_CASE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Abstract</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__ABSTRACT = USE_CASE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Active</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__ACTIVE = USE_CASE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Business</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__BUSINESS = USE_CASE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Parent Actor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__PARENT_ACTOR = USE_CASE_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Use Case</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__USE_CASE = USE_CASE_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Actor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_FEATURE_COUNT = USE_CASE_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseImpl <em>Use Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UseCaseImpl
   * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getUseCase()
   * @generated
   */
  int USE_CASE = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__NAME = USE_CASE_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Included Use Case</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__INCLUDED_USE_CASE = USE_CASE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Extended Use Case</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__EXTENDED_USE_CASE = USE_CASE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__DESCRIPTION = USE_CASE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Use Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_FEATURE_COUNT = USE_CASE_ELEMENT_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.mdd.umltextual.umlTextual.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.ModelElement <em>Model Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model Element</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.ModelElement
   * @generated
   */
  EClass getModelElement();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.ModelElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.ModelElement#getName()
   * @see #getModelElement()
   * @generated
   */
  EAttribute getModelElement_Name();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Package <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Package
   * @generated
   */
  EClass getPackage();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Package#getInstantiable <em>Instantiable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Instantiable</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Package#getInstantiable()
   * @see #getPackage()
   * @generated
   */
  EAttribute getPackage_Instantiable();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Package#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Package#getType()
   * @see #getPackage()
   * @generated
   */
  EAttribute getPackage_Type();

  /**
   * Returns the meta object for the reference '{@link br.ufes.mdd.umltextual.umlTextual.Package#getParentPackage <em>Parent Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Parent Package</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Package#getParentPackage()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_ParentPackage();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.mdd.umltextual.umlTextual.Package#getDomainSpecificTypes <em>Domain Specific Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Domain Specific Types</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Package#getDomainSpecificTypes()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_DomainSpecificTypes();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.mdd.umltextual.umlTextual.Package#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Package#getElements()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_Elements();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Class
   * @generated
   */
  EClass getClass_();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Class#getStereotype <em>Stereotype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Stereotype</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Class#getStereotype()
   * @see #getClass_()
   * @generated
   */
  EAttribute getClass_Stereotype();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Class#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Class#getVisibility()
   * @see #getClass_()
   * @generated
   */
  EAttribute getClass_Visibility();

  /**
   * Returns the meta object for the reference '{@link br.ufes.mdd.umltextual.umlTextual.Class#getParentClass <em>Parent Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Parent Class</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Class#getParentClass()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_ParentClass();

  /**
   * Returns the meta object for the reference list '{@link br.ufes.mdd.umltextual.umlTextual.Class#getInterface <em>Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Interface</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Class#getInterface()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Interface();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.mdd.umltextual.umlTextual.Class#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Class#getAttributes()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.mdd.umltextual.umlTextual.Class#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Methods</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Class#getMethods()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Methods();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Interface <em>Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interface</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Interface
   * @generated
   */
  EClass getInterface();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Interface#getStereotype <em>Stereotype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Stereotype</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Interface#getStereotype()
   * @see #getInterface()
   * @generated
   */
  EAttribute getInterface_Stereotype();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Interface#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Interface#getVisibility()
   * @see #getInterface()
   * @generated
   */
  EAttribute getInterface_Visibility();

  /**
   * Returns the meta object for the reference '{@link br.ufes.mdd.umltextual.umlTextual.Interface#getParentClass <em>Parent Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Parent Class</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Interface#getParentClass()
   * @see #getInterface()
   * @generated
   */
  EReference getInterface_ParentClass();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.mdd.umltextual.umlTextual.Interface#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Interface#getAttributes()
   * @see #getInterface()
   * @generated
   */
  EReference getInterface_Attributes();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.AttributeType <em>Attribute Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Type</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.AttributeType
   * @generated
   */
  EClass getAttributeType();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.AttributeType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.AttributeType#getName()
   * @see #getAttributeType()
   * @generated
   */
  EAttribute getAttributeType_Name();

  /**
   * Returns the meta object for the reference '{@link br.ufes.mdd.umltextual.umlTextual.AttributeType#getDomainType <em>Domain Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Domain Type</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.AttributeType#getDomainType()
   * @see #getAttributeType()
   * @generated
   */
  EReference getAttributeType_DomainType();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.DomainSpecificType <em>Domain Specific Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain Specific Type</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.DomainSpecificType
   * @generated
   */
  EClass getDomainSpecificType();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.DomainSpecificType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.DomainSpecificType#getName()
   * @see #getDomainSpecificType()
   * @generated
   */
  EAttribute getDomainSpecificType_Name();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.DomainSpecificType#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.DomainSpecificType#getDescription()
   * @see #getDomainSpecificType()
   * @generated
   */
  EAttribute getDomainSpecificType_Description();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Attribute#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Attribute#getVisibility()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Visibility();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.mdd.umltextual.umlTextual.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Type();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Attribute#getMultiplicity <em>Multiplicity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multiplicity</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Attribute#getMultiplicity()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Multiplicity();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Method <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Method
   * @generated
   */
  EClass getMethod();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Method#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Method#getVisibility()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Visibility();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Method#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Method#getName()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Name();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.mdd.umltextual.umlTextual.Method#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Method#getParameters()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.mdd.umltextual.umlTextual.Method#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Type</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Method#getReturnType()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_ReturnType();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.mdd.umltextual.umlTextual.Parameter#getParameterType <em>Parameter Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter Type</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Parameter#getParameterType()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_ParameterType();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector <em>Association Connector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Association Connector</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.AssociationConnector
   * @generated
   */
  EClass getAssociationConnector();

  /**
   * Returns the meta object for the reference '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getClass1 <em>Class1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Class1</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getClass1()
   * @see #getAssociationConnector()
   * @generated
   */
  EReference getAssociationConnector_Class1();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getMultiplicity1 <em>Multiplicity1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multiplicity1</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getMultiplicity1()
   * @see #getAssociationConnector()
   * @generated
   */
  EAttribute getAssociationConnector_Multiplicity1();

  /**
   * Returns the meta object for the reference '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getClass2 <em>Class2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Class2</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getClass2()
   * @see #getAssociationConnector()
   * @generated
   */
  EReference getAssociationConnector_Class2();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getMultiplicity2 <em>Multiplicity2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multiplicity2</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.AssociationConnector#getMultiplicity2()
   * @see #getAssociationConnector()
   * @generated
   */
  EAttribute getAssociationConnector_Multiplicity2();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Association <em>Association</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Association</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Association
   * @generated
   */
  EClass getAssociation();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Association#getNavigation1 <em>Navigation1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Navigation1</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Association#getNavigation1()
   * @see #getAssociation()
   * @generated
   */
  EAttribute getAssociation_Navigation1();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Association#getNavigation2 <em>Navigation2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Navigation2</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Association#getNavigation2()
   * @see #getAssociation()
   * @generated
   */
  EAttribute getAssociation_Navigation2();

  /**
   * Returns the meta object for the reference '{@link br.ufes.mdd.umltextual.umlTextual.Association#getClass_ <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Class</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Association#getClass_()
   * @see #getAssociation()
   * @generated
   */
  EReference getAssociation_Class();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Aggregation <em>Aggregation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aggregation</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Aggregation
   * @generated
   */
  EClass getAggregation();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Aggregation#getNavigation <em>Navigation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Navigation</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Aggregation#getNavigation()
   * @see #getAggregation()
   * @generated
   */
  EAttribute getAggregation_Navigation();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Composition <em>Composition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Composition</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Composition
   * @generated
   */
  EClass getComposition();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Composition#getNavigation <em>Navigation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Navigation</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Composition#getNavigation()
   * @see #getComposition()
   * @generated
   */
  EAttribute getComposition_Navigation();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.UseCaseDiagram <em>Use Case Diagram</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case Diagram</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.UseCaseDiagram
   * @generated
   */
  EClass getUseCaseDiagram();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufes.mdd.umltextual.umlTextual.UseCaseDiagram#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.UseCaseDiagram#getElements()
   * @see #getUseCaseDiagram()
   * @generated
   */
  EReference getUseCaseDiagram_Elements();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.UseCaseElement <em>Use Case Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case Element</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.UseCaseElement
   * @generated
   */
  EClass getUseCaseElement();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.UseCaseElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.UseCaseElement#getName()
   * @see #getUseCaseElement()
   * @generated
   */
  EAttribute getUseCaseElement_Name();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.Actor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actor</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Actor
   * @generated
   */
  EClass getActor();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Actor#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Actor#getVisibility()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Visibility();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Actor#getAbstract <em>Abstract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Abstract</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Actor#getAbstract()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Abstract();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Actor#getActive <em>Active</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Active</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Actor#getActive()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Active();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.Actor#getBusiness <em>Business</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Business</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Actor#getBusiness()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Business();

  /**
   * Returns the meta object for the containment reference '{@link br.ufes.mdd.umltextual.umlTextual.Actor#getParentActor <em>Parent Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parent Actor</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Actor#getParentActor()
   * @see #getActor()
   * @generated
   */
  EReference getActor_ParentActor();

  /**
   * Returns the meta object for the reference list '{@link br.ufes.mdd.umltextual.umlTextual.Actor#getUseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Use Case</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.Actor#getUseCase()
   * @see #getActor()
   * @generated
   */
  EReference getActor_UseCase();

  /**
   * Returns the meta object for class '{@link br.ufes.mdd.umltextual.umlTextual.UseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.UseCase
   * @generated
   */
  EClass getUseCase();

  /**
   * Returns the meta object for the reference list '{@link br.ufes.mdd.umltextual.umlTextual.UseCase#getIncludedUseCase <em>Included Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Included Use Case</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.UseCase#getIncludedUseCase()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_IncludedUseCase();

  /**
   * Returns the meta object for the reference list '{@link br.ufes.mdd.umltextual.umlTextual.UseCase#getExtendedUseCase <em>Extended Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Extended Use Case</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.UseCase#getExtendedUseCase()
   * @see #getUseCase()
   * @generated
   */
  EReference getUseCase_ExtendedUseCase();

  /**
   * Returns the meta object for the attribute '{@link br.ufes.mdd.umltextual.umlTextual.UseCase#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see br.ufes.mdd.umltextual.umlTextual.UseCase#getDescription()
   * @see #getUseCase()
   * @generated
   */
  EAttribute getUseCase_Description();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UmlTextualFactory getUmlTextualFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.ModelImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ModelElementImpl <em>Model Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.ModelElementImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getModelElement()
     * @generated
     */
    EClass MODEL_ELEMENT = eINSTANCE.getModelElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_ELEMENT__NAME = eINSTANCE.getModelElement_Name();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.PackageImpl <em>Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.PackageImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getPackage()
     * @generated
     */
    EClass PACKAGE = eINSTANCE.getPackage();

    /**
     * The meta object literal for the '<em><b>Instantiable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE__INSTANTIABLE = eINSTANCE.getPackage_Instantiable();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE__TYPE = eINSTANCE.getPackage_Type();

    /**
     * The meta object literal for the '<em><b>Parent Package</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__PARENT_PACKAGE = eINSTANCE.getPackage_ParentPackage();

    /**
     * The meta object literal for the '<em><b>Domain Specific Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__DOMAIN_SPECIFIC_TYPES = eINSTANCE.getPackage_DomainSpecificTypes();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__ELEMENTS = eINSTANCE.getPackage_Elements();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.ElementImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.ClassImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getClass_()
     * @generated
     */
    EClass CLASS = eINSTANCE.getClass_();

    /**
     * The meta object literal for the '<em><b>Stereotype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS__STEREOTYPE = eINSTANCE.getClass_Stereotype();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS__VISIBILITY = eINSTANCE.getClass_Visibility();

    /**
     * The meta object literal for the '<em><b>Parent Class</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__PARENT_CLASS = eINSTANCE.getClass_ParentClass();

    /**
     * The meta object literal for the '<em><b>Interface</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__INTERFACE = eINSTANCE.getClass_Interface();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__ATTRIBUTES = eINSTANCE.getClass_Attributes();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__METHODS = eINSTANCE.getClass_Methods();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.InterfaceImpl <em>Interface</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.InterfaceImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getInterface()
     * @generated
     */
    EClass INTERFACE = eINSTANCE.getInterface();

    /**
     * The meta object literal for the '<em><b>Stereotype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERFACE__STEREOTYPE = eINSTANCE.getInterface_Stereotype();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERFACE__VISIBILITY = eINSTANCE.getInterface_Visibility();

    /**
     * The meta object literal for the '<em><b>Parent Class</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERFACE__PARENT_CLASS = eINSTANCE.getInterface_ParentClass();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERFACE__ATTRIBUTES = eINSTANCE.getInterface_Attributes();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.AttributeTypeImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAttributeType()
     * @generated
     */
    EClass ATTRIBUTE_TYPE = eINSTANCE.getAttributeType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_TYPE__NAME = eINSTANCE.getAttributeType_Name();

    /**
     * The meta object literal for the '<em><b>Domain Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_TYPE__DOMAIN_TYPE = eINSTANCE.getAttributeType_DomainType();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.DomainSpecificTypeImpl <em>Domain Specific Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.DomainSpecificTypeImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getDomainSpecificType()
     * @generated
     */
    EClass DOMAIN_SPECIFIC_TYPE = eINSTANCE.getDomainSpecificType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAIN_SPECIFIC_TYPE__NAME = eINSTANCE.getDomainSpecificType_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAIN_SPECIFIC_TYPE__DESCRIPTION = eINSTANCE.getDomainSpecificType_Description();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.AttributeImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__VISIBILITY = eINSTANCE.getAttribute_Visibility();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '<em><b>Multiplicity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__MULTIPLICITY = eINSTANCE.getAttribute_Multiplicity();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.MethodImpl <em>Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.MethodImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getMethod()
     * @generated
     */
    EClass METHOD = eINSTANCE.getMethod();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__VISIBILITY = eINSTANCE.getMethod_Visibility();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__NAME = eINSTANCE.getMethod_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__PARAMETERS = eINSTANCE.getMethod_Parameters();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__RETURN_TYPE = eINSTANCE.getMethod_ReturnType();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.ParameterImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Parameter Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__PARAMETER_TYPE = eINSTANCE.getParameter_ParameterType();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AssociationConnectorImpl <em>Association Connector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.AssociationConnectorImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAssociationConnector()
     * @generated
     */
    EClass ASSOCIATION_CONNECTOR = eINSTANCE.getAssociationConnector();

    /**
     * The meta object literal for the '<em><b>Class1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_CONNECTOR__CLASS1 = eINSTANCE.getAssociationConnector_Class1();

    /**
     * The meta object literal for the '<em><b>Multiplicity1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATION_CONNECTOR__MULTIPLICITY1 = eINSTANCE.getAssociationConnector_Multiplicity1();

    /**
     * The meta object literal for the '<em><b>Class2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_CONNECTOR__CLASS2 = eINSTANCE.getAssociationConnector_Class2();

    /**
     * The meta object literal for the '<em><b>Multiplicity2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATION_CONNECTOR__MULTIPLICITY2 = eINSTANCE.getAssociationConnector_Multiplicity2();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AssociationImpl <em>Association</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.AssociationImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAssociation()
     * @generated
     */
    EClass ASSOCIATION = eINSTANCE.getAssociation();

    /**
     * The meta object literal for the '<em><b>Navigation1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATION__NAVIGATION1 = eINSTANCE.getAssociation_Navigation1();

    /**
     * The meta object literal for the '<em><b>Navigation2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATION__NAVIGATION2 = eINSTANCE.getAssociation_Navigation2();

    /**
     * The meta object literal for the '<em><b>Class</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION__CLASS = eINSTANCE.getAssociation_Class();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.AggregationImpl <em>Aggregation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.AggregationImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getAggregation()
     * @generated
     */
    EClass AGGREGATION = eINSTANCE.getAggregation();

    /**
     * The meta object literal for the '<em><b>Navigation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGGREGATION__NAVIGATION = eINSTANCE.getAggregation_Navigation();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.CompositionImpl <em>Composition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.CompositionImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getComposition()
     * @generated
     */
    EClass COMPOSITION = eINSTANCE.getComposition();

    /**
     * The meta object literal for the '<em><b>Navigation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOSITION__NAVIGATION = eINSTANCE.getComposition_Navigation();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseDiagramImpl <em>Use Case Diagram</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UseCaseDiagramImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getUseCaseDiagram()
     * @generated
     */
    EClass USE_CASE_DIAGRAM = eINSTANCE.getUseCaseDiagram();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE_DIAGRAM__ELEMENTS = eINSTANCE.getUseCaseDiagram_Elements();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseElementImpl <em>Use Case Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UseCaseElementImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getUseCaseElement()
     * @generated
     */
    EClass USE_CASE_ELEMENT = eINSTANCE.getUseCaseElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE_ELEMENT__NAME = eINSTANCE.getUseCaseElement_Name();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.ActorImpl <em>Actor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.ActorImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getActor()
     * @generated
     */
    EClass ACTOR = eINSTANCE.getActor();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__VISIBILITY = eINSTANCE.getActor_Visibility();

    /**
     * The meta object literal for the '<em><b>Abstract</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__ABSTRACT = eINSTANCE.getActor_Abstract();

    /**
     * The meta object literal for the '<em><b>Active</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__ACTIVE = eINSTANCE.getActor_Active();

    /**
     * The meta object literal for the '<em><b>Business</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__BUSINESS = eINSTANCE.getActor_Business();

    /**
     * The meta object literal for the '<em><b>Parent Actor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTOR__PARENT_ACTOR = eINSTANCE.getActor_ParentActor();

    /**
     * The meta object literal for the '<em><b>Use Case</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTOR__USE_CASE = eINSTANCE.getActor_UseCase();

    /**
     * The meta object literal for the '{@link br.ufes.mdd.umltextual.umlTextual.impl.UseCaseImpl <em>Use Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UseCaseImpl
     * @see br.ufes.mdd.umltextual.umlTextual.impl.UmlTextualPackageImpl#getUseCase()
     * @generated
     */
    EClass USE_CASE = eINSTANCE.getUseCase();

    /**
     * The meta object literal for the '<em><b>Included Use Case</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__INCLUDED_USE_CASE = eINSTANCE.getUseCase_IncludedUseCase();

    /**
     * The meta object literal for the '<em><b>Extended Use Case</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASE__EXTENDED_USE_CASE = eINSTANCE.getUseCase_ExtendedUseCase();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE__DESCRIPTION = eINSTANCE.getUseCase_Description();

  }

} //UmlTextualPackage
