/*
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.serializer;

import br.ufes.mdd.umltextual.services.UmlTextualGrammarAccess;
import br.ufes.mdd.umltextual.umlTextual.Aggregation;
import br.ufes.mdd.umltextual.umlTextual.Association;
import br.ufes.mdd.umltextual.umlTextual.Attribute;
import br.ufes.mdd.umltextual.umlTextual.AttributeType;
import br.ufes.mdd.umltextual.umlTextual.Composition;
import br.ufes.mdd.umltextual.umlTextual.DomainSpecificType;
import br.ufes.mdd.umltextual.umlTextual.Model;
import br.ufes.mdd.umltextual.umlTextual.UmlTextualPackage;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class UmlTextualSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private UmlTextualGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == UmlTextualPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case UmlTextualPackage.AGGREGATION:
				sequence_Aggregation(context, (Aggregation) semanticObject); 
				return; 
			case UmlTextualPackage.ASSOCIATION:
				sequence_Association(context, (Association) semanticObject); 
				return; 
			case UmlTextualPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case UmlTextualPackage.ATTRIBUTE_TYPE:
				sequence_AttributeType(context, (AttributeType) semanticObject); 
				return; 
			case UmlTextualPackage.CLASS:
				sequence_Class(context, (br.ufes.mdd.umltextual.umlTextual.Class) semanticObject); 
				return; 
			case UmlTextualPackage.COMPOSITION:
				sequence_Composition(context, (Composition) semanticObject); 
				return; 
			case UmlTextualPackage.DOMAIN_SPECIFIC_TYPE:
				sequence_DomainSpecificType(context, (DomainSpecificType) semanticObject); 
				return; 
			case UmlTextualPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case UmlTextualPackage.PACKAGE:
				sequence_Package(context, (br.ufes.mdd.umltextual.umlTextual.Package) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     AssociationConnector returns Aggregation
	 *     Aggregation returns Aggregation
	 *
	 * Constraint:
	 *     (
	 *         (name=ID | name=Unamed) 
	 *         class1=[Class|ID] 
	 *         multiplicity1=Multiplicity 
	 *         navigation=Navigation? 
	 *         class2=[Class|ID] 
	 *         multiplicity2=Multiplicity
	 *     )
	 */
	protected void sequence_Aggregation(ISerializationContext context, Aggregation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AssociationConnector returns Association
	 *     Association returns Association
	 *
	 * Constraint:
	 *     (
	 *         (name=ID | name=Unamed) 
	 *         navigation1=Navigation? 
	 *         class1=[Class|ID] 
	 *         multiplicity1=Multiplicity 
	 *         navigation2=Navigation? 
	 *         class2=[Class|ID] 
	 *         multiplicity2=Multiplicity
	 *     )
	 */
	protected void sequence_Association(ISerializationContext context, Association semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AttributeType returns AttributeType
	 *
	 * Constraint:
	 *     {AttributeType}
	 */
	protected void sequence_AttributeType(ISerializationContext context, AttributeType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (visibility=Visibility? name=ID type=AttributeType multiplicity=Multiplicity?)
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Class returns Class
	 *
	 * Constraint:
	 *     (stereotype=ID? visibility=Visibility? name=ID parentClass=Class? attributes+=Attribute*)
	 */
	protected void sequence_Class(ISerializationContext context, br.ufes.mdd.umltextual.umlTextual.Class semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AssociationConnector returns Composition
	 *     Composition returns Composition
	 *
	 * Constraint:
	 *     (
	 *         (name=ID | name=Unamed) 
	 *         class1=[Class|ID] 
	 *         multiplicity1=Multiplicity 
	 *         navigation=Navigation? 
	 *         class2=[Class|ID] 
	 *         multiplicity2=Multiplicity
	 *     )
	 */
	protected void sequence_Composition(ISerializationContext context, Composition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AttributeType returns DomainSpecificType
	 *     DomainSpecificType returns DomainSpecificType
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_DomainSpecificType(ISerializationContext context, DomainSpecificType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, UmlTextualPackage.Literals.DOMAIN_SPECIFIC_TYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, UmlTextualPackage.Literals.DOMAIN_SPECIFIC_TYPE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDomainSpecificTypeAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     packages+=Package+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Package returns Package
	 *
	 * Constraint:
	 *     ((type='package' | type='subsystem') name=ID classes+=Class* associations+=AssociationConnector*)
	 */
	protected void sequence_Package(ISerializationContext context, br.ufes.mdd.umltextual.umlTextual.Package semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
