/*
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.serializer;

import br.ufes.mdd.umltextual.services.UmlTextualGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class UmlTextualSyntacticSequencer extends AbstractSyntacticSequencer {

	protected UmlTextualGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Association_UndirectedKeyword_0_q;
	protected AbstractElementAlias match_AttributeType_BooleanKeyword_3_1_or_ByteKeyword_4_1_or_CharKeyword_5_1_or_DoubleKeyword_2_1_or_FloatKeyword_6_1_or_IntKeyword_1_1_or_LongKeyword_8_1_or_ShortKeyword_7_1_or_StringKeyword_0_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (UmlTextualGrammarAccess) access;
		match_Association_UndirectedKeyword_0_q = new TokenAlias(false, true, grammarAccess.getAssociationAccess().getUndirectedKeyword_0());
		match_AttributeType_BooleanKeyword_3_1_or_ByteKeyword_4_1_or_CharKeyword_5_1_or_DoubleKeyword_2_1_or_FloatKeyword_6_1_or_IntKeyword_1_1_or_LongKeyword_8_1_or_ShortKeyword_7_1_or_StringKeyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getBooleanKeyword_3_1()), new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getByteKeyword_4_1()), new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getCharKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getDoubleKeyword_2_1()), new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getFloatKeyword_6_1()), new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getIntKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getLongKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getShortKeyword_7_1()), new TokenAlias(false, false, grammarAccess.getAttributeTypeAccess().getStringKeyword_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Association_UndirectedKeyword_0_q.equals(syntax))
				emit_Association_UndirectedKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AttributeType_BooleanKeyword_3_1_or_ByteKeyword_4_1_or_CharKeyword_5_1_or_DoubleKeyword_2_1_or_FloatKeyword_6_1_or_IntKeyword_1_1_or_LongKeyword_8_1_or_ShortKeyword_7_1_or_StringKeyword_0_1.equals(syntax))
				emit_AttributeType_BooleanKeyword_3_1_or_ByteKeyword_4_1_or_CharKeyword_5_1_or_DoubleKeyword_2_1_or_FloatKeyword_6_1_or_IntKeyword_1_1_or_LongKeyword_8_1_or_ShortKeyword_7_1_or_StringKeyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'undirected'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'association' name=ID
	 *     (rule start) (ambiguity) 'association' name=Unamed
	 */
	protected void emit_Association_UndirectedKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         'string' | 
	  *         'int' | 
	  *         'double' | 
	  *         'boolean' | 
	  *         'byte' | 
	  *         'char' | 
	  *         'float' | 
	  *         'short' | 
	  *         'long'
	  *     )
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_AttributeType_BooleanKeyword_3_1_or_ByteKeyword_4_1_or_CharKeyword_5_1_or_DoubleKeyword_2_1_or_FloatKeyword_6_1_or_IntKeyword_1_1_or_LongKeyword_8_1_or_ShortKeyword_7_1_or_StringKeyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
