/*
 * generated by Xtext 2.25.0
 */
package br.ufes.mdd.umltextual.ide;


/**
 * Use this class to register ide components.
 */
public class UmlTextualIdeModule extends AbstractUmlTextualIdeModule {
}
